version: 2

builds:
  - main: ./cmd/librarr/
    binary: librarr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X github.com/jamie75/librarr/internal/api.Version={{.Version}}
      - -X github.com/jamie75/librarr/internal/api.BuildTime={{.Date}}
      - -X github.com/jamie75/librarr/internal/api.Commit={{.ShortCommit}}
      - -X github.com/jamie75/librarr/internal/api.Channel={{.Version}}

archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
